---

- name: Start the cadvisor
  docker_container:
    name: "cadvisor"
    image: "google/cadvisor"
    command: "-storage_driver_db=cadvisor -storage_driver_host={{ hostvars[influxdb_node]['ansible_' + hostvars[influxdb_node]['control_network']]['ipv4']['address'] }}:8086 -storage_driver=influxdb --housekeeping_interval={{ cadvisor.housekeeping_interval }}"
    detach: True
    ports:
      # don't bind to the host port 8080 since swift is using it by default
      - "8888:8080"
    state: started
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/etc/hostname:/etc/machine-id"
