---
- name: Common configuration
  hosts: all
  roles:
    - { role: common,
        tags: common }

- name: Deploy the grafana
  hosts: control
  roles:
    - { role: grafana,
        tags: grafana,
        when: enable_monitoring | bool }

- name: Install registry
  hosts: all
  roles :
    - { role: registry,
        tags: registry }

- name: Apply role chrony
  hosts: all
  roles:
    - { role: chrony,
        tags: chrony }

- name: Deploy influxdb
  hosts: control
  roles:
    - { role: influxdb,
        tags: influxdb,
        when: enable_monitoring | bool }

- name: Deploy the grafana
  hosts: control
  roles:
    - { role: grafana,
        tags: grafana,
        when: enable_monitoring | bool }

- name: MariaDB deployment
  hosts: database[0]
  roles:
    - { role: database,
        tags: mariadb,
        when: db == "mariadb" }

- name: "{{ db }} deployment (Non Mariadb)"
  hosts: database
  roles:
   - { role: database,
       tags: "{{ db }}",
       when: db != "mariadb" }

- name: Install monitoring agents
  hosts: database
  roles:
    - { role: cadvisor,
        tags: cadvisor,
        when: enable_monitoring | bool  }
    - { role: collectd,
        tags: collectd,
        when: (db == "mariadb" or db == "galera") and (enable_monitoring | bool) }

- name: Sysbench deployment
  hosts: database
  roles:
    - { role: sysbench,
        tags: sysbench }
