---
# See https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html
- name: Mount /database-cockroachdb in tmpfs to store CockroachDB
  mount:
    path: /database-cockroachdb
    src: tmpfs
    fstype: tmpfs
    state: mounted
    opts: size=16G

- name: Start the first CockroachDB node
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach:v2.0.4"
    # hostname: "{{ inventory_hostname }}"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - "/database-cockroachdb:/cockroach/cockroach-data"
    command: >
      start --insecure
      --advertise-host="{{ hostvars[inventory_hostname]['ansible_'+ database_network]['ipv4']['address'] }}"
  when:
    - inventory_hostname == dbmaster_node

- name: Waiting for the first CockroachDB to be ready
  wait_for:
    host: "{{ hostvars[dbmaster_node]['ansible_' + database_network]['ipv4']['address'] }}"
    port: 26257
  when:
    - inventory_hostname == dbmaster_node

- name: Start other CockroachDB nodes
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach:v2.0.4"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - "/database-cockroachdb:/cockroach/cockroach-data"
    command: >
      start --insecure
      --join="{{ hostvars[dbmaster_node]['ansible_'+ database_network].ipv4.address }}"
      --advertise-host="{{ hostvars[inventory_hostname]['ansible_'+ database_network]['ipv4']['address'] }}"
  when:
    - inventory_hostname != dbmaster_node

- name: Waiting for other CockroachDBs to be ready
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + database_network]['ipv4']['address'] }}"
    port: 26257
  when:
    - inventory_hostname != dbmaster_node
